branch-defaults:
  add-webpack:
    environment: develop-docker
  master:
    environment: null
global:
  application_name: Resily
  default_ec2_keyname: resily.pem
  default_platform: Multi-container Docker 18.06.1-ce (Generic)
  default_region: ap-northeast-1
  sc: git
  workspace_type: Application
