development:
  adapter: async

test:
  adapter: async

staging:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: resily_production

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: resily_production
